name: unit-test-firestore-rules
on: pull_request
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '10.x'

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Install dependencies
        working-directory: ./test
        run: npm install

      - name: Run Firebase emulators
        run: firebase emulators:start

      - name: Run unit tests
        working-directory: ./test
        run: npm test
